export const environment = {
  production: true,
  entorno: 'prod',
  autenticacion: true,
  notificaciones: true,
  menuApps: false,
  appname: 'castor_cliente',
  appMenu: 'castor_cliente',
  ACADEMICA_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/academica_jbpm/v2/',
  POLUX_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_crud/v1/',
  POLUX_MID_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/polux_mid/v1/',
  SESIONES_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/sesiones_crud/v2/',
  GESTOR_DOCUMENTAL_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/gestor_documental_mid/v1/',
  CASTOR_CV_TIPO_DOCUMENTO_ID: 0, // TODO: definir tipo de documento definitivo
  OIKOS_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/oikos_crud_api/v1/',
  CASTOR_MID_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/castor_mid/v1',
  PARAMETROS_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/',
  TERCEROS_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/terceros_crud/v1/',
  CONFIGURACION_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/configuracion_crud_api/v1/',
  CONF_MENU_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/configuracion_crud_api/v1/menu_opcion_padre/ArbolMenus/',
  NOTIFICACION_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/notificacion_mid/v1/',
  API_BASES: {
    castor_mid: 'http://localhost:8080/v1/',
    autenticacion_mid: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/autenticacion_mid/v1/',
    academica: 'http://<HOST_ACADEMICA>/v1/',
    polux_mid: 'http://<HOST_POLUX_MID>/v1/',
    polux: 'http://<HOST_POLUX>/v1/',
    gestor_doc_mid: 'http://<HOST_GESTOR_DOC_MID>/v1/',
    oikos: 'http://<HOST_OIKOS>/v2/',
    dependencias_api: 'http://<HOST_OIKOS>/v2/',
    castor_crud: 'http://localhost:8081/v1/',
  },
  TOKEN: {
    AUTORIZATION_URL: 'https://autenticacion.portaloas.udistrital.edu.co/oauth2/authorize',
    CLIENTE_ID: 'solicitar token a arquitectura',
    RESPONSE_TYPE: 'id_token token',
    SCOPE: 'openid email role documento',
    REDIRECT_URL: 'https://oas.portaloas.udistrital.edu.co',
    SIGN_OUT_URL: 'https://autenticacion.portaloas.udistrital.edu.co/oidc/logout',
    SIGN_OUT_REDIRECT_URL: 'https://oas.portaloas.udistrital.edu.co',
    AUTENTICACION_MID: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/autenticacion_mid/v1/token/userRol',
  },
};

